### ISSUE TITLE
setting up actions

### ISSUE THREAD

**Issue by pr4deepr** [BioimageAnalysisCoreWEHI/napari_lattice#1]
Hi @haesleinhuepf 
      I'm testing out napari_lattice and learning how to publish it as a pypi package. 
I'm having trouble setting up github actions and automated testing/deployment. 
Would you mind helping me out with this?

Cheers

Pradeep

**Comment by pr4deepr** [comment]
THanks @haesleinhuepf 
BTW, I had two tests which I had removed. 
I've added them back and maybe you can let me know if they work well or not:
https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/tree/master/src/napari_lattice/_tests
I had trouble with github actions and running the tests. 

In regard to publishing on pypi, I did try the commands you mentioned, and there is a package here
https://pypi.org/project/napari-lattice/

However, I cannot see it in napari-hub.. not sure what I'm doing wrong...

**Comment by haesleinhuepf** [comment]
Just a note: The tests are currently failing (locally) because of changes we introduced in [pyclesperanto_prototype 0.17.3](https://github.com/clEsperanto/pyclesperanto_prototype/releases/tag/0.17.3). I'll fix that in my PR.
