### ISSUE TITLE
Use config file for no GUI processing

### ISSUE THREAD

**Issue by pr4deepr** [BioimageAnalysisCoreWEHI/napari_lattice#12]
The napari-lattice plugin has the option for batch processing within the terminal. Considering the addition of more functionalities, the number of arguments isgrowing. This can get confusing and require really long command lines which is not user-friendly. (not that running in the terminal makes it any easier 😝 )

Instead, use a yaml config file. 
Syntax should be: 

`napari-lattice --config "location-of-config-file"`

Arguments: https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/wiki/6.-Batch-Processing

**Comment by DrLachie** [comment]
I've cretaed a branch that allows an optional --config yml file, but still works with the CLI if preferred. Also should set defaults if parameters are missing in config file.

**Comment by DrLachie** [comment]
Have also added a --roi_number argument that if set will only crop* the one roi. This way we can parallelise easily across ROIs. 

* it _should_ also work with workflow_crop and possible decon but I've not been able to test these yet.

**Comment by pr4deepr** [comment]
If its all done, could you create a pull request? I can test it as well then.

**Comment by DrLachie** [comment]
Hold off on the merge - not currently working for all options (decon specifically but need to check workflows as well) will fix

**Comment by pr4deepr** [comment]
Implemented here: 
https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/pull/20
