### ISSUE TITLE
Can this method applied to the Image captured by the Elyra  lattice SIM (zeiss)?

### ISSUE THREAD

**Issue by cindy12-gao** [BioimageAnalysisCoreWEHI/napari_lattice#54]
hi~ Can the image which captured by elyra lattice SIM (https://www.zeiss.com/microscopy/en/products/light-microscopes/super-resolution-microscopes/elyra-7.html) also use this method to process?

**Comment by pr4deepr** [comment]
Hi @cindy12-gao 
   I believe this is super resolution and it is different than acquisition of lattice lightsheet. This plugin cannot be used for processing data from the elyra as far as I know.

I saw your question on 'napari-sim-lattice' repo as well. 
I highly recommend you post your questions on imagesc forum (https://forum.image.sc/) to get suggestions on tools you could use? You will have many experts and developers of tools who could point you in the right direction.


Cheers
Pradeep
