### ISSUE TITLE
Small ROI Bug

### ISSUE THREAD

**Issue by multimeric** [BioimageAnalysisCoreWEHI/napari_lattice#63]
Just adding this so I don't forget. Small ROI issue:

<img width="624" alt="Screen Shot 2024-08-23 at 1 31 17 pm" src="https://github.com/user-attachments/assets/104bde0f-790c-4529-a179-4e2ca4f563a1">

I think this is because the set of 2 ROIs are being treated as 1 ROI in this scenario where the user uploads a ZIP file. Should be an easy fix

**Comment by multimeric** [comment]
Hmm, so this happens when you import an ROI file with multiple ROIs into Napari, and then select it as a cropping layer. This results in a single cropping layer that contains multiple shapes. Is the correct solution to load this into Napari as multiple shape layers?

**Comment by pr4deepr** [comment]
Ideally, you would iterate through all the polygons in a shape layer.. depending on the experiment you could have anywherefrom shapes for our datasets. This isn't fixed of course and can vary a fair bit.

**Comment by multimeric** [comment]
Okay, so if the user uploads two ZIP files, each of which has 2 ROIs, you would expect there to be 2 Napari shape layers, but 4 ROI results when we run the processing?

**Comment by pr4deepr** [comment]
If there are multiple shapes layers in napari, then the rois processed would depend on how many layers the user has selected.  If the user selected both layers and clicks Save, then yes, we would process all 4 ROIs.

**Comment by pr4deepr** [comment]
Preview used to work even though there was an warning/error.. but doesn't anymore with Preview and Crop
