### ISSUE TITLE
crop with workflow processing only first ROI

### ISSUE THREAD

**Issue by pr4deepr** [BioimageAnalysisCoreWEHI/napari_lattice#66]
CLI:

When running Crop in CLI by passing an ROIlist as a zip file and specifying roi_subset in yaml-config, I can save multiple ROIs. 

However, if I run this with a workflow, the workflow gets executed but only for the first ROI. Rest of the ROIs or crops do not get processed.

@multimeric

**Comment by multimeric** [comment]
So it happens when you enable workflow + crop in the CLI?

**Comment by pr4deepr** [comment]
Yes
