### ISSUE TITLE
Make the Python API and CLI parameters have uniform names

### ISSUE THREAD

**Issue by multimeric** [BioimageAnalysisCoreWEHI/napari_lattice#73]
I believe they had distinct names with the intention of making the CLI backwards compatible, but consensus is that it would be more intuitive if they had the same names. This would also simplify the code quite a lot.

**Comment by DrLachie** [comment]
Working on this - also will change "psf_num_iter" to "decon_num_iter" or similar as we're doing iterations of deconvolution, not iterating over psfs
