### ISSUE TITLE
Does not recognise channels in czi file

### ISSUE THREAD

**Issue by Eddymorphling** [BioimageAnalysisCoreWEHI/napari_lattice#8]
Folks, 
Thanks for making this plugin :) I have been trying to find a way to deskew/deconvolve that is not on ZEN Blue so this is great! 

Here is the issue I faced - I loaded a skewed lattice light sheet dataset but `napari-lattice` fails to recognize the "channel" dimension in the czi file. I did try the below step  as mentioned in the github page, but that did not help.

> "If the channels are split into different layers, press Shift and select all the channels. Right click on the highlighted layers and then click Merge to stack."

Here is a screenshot of the error. Any ideas what the issue is? I use `napari-czifile2` to read czi files in napari
Thanks!

![image](https://user-images.githubusercontent.com/67712116/188234907-0c25e50a-2705-4c4a-a29a-52721767750c.png)

**Comment by pr4deepr** [comment]
Thanks @Eddymorphling 
Apologies for not responding to this issue and sorry you're running into trouble.

Could you try updating the plugin, as I've released 0.1.8 just now as there were a few bugs. It may take a few minutes/hours to update. 

I use aicsimageio for reading czi files, but you can import any custom napari layer data. 
Could you show me the output from the terminal and the "traceback"?
When you try merging the layers, in this case, RFP and GFP and re-initialize the plugin, what happens?
Do you still get the same error?

If you are still getting errors after the update, would you mind sharing the file? Happy to have a look. 

BTW, I've updated the documentation and moved it all to the [Wiki](https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/wiki)

**Comment by pr4deepr** [comment]
Should be fixed in 0.1.9 release. 
More info here: 
https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/wiki/1.-Opening-files

Otherwise, I'd recommend using napari-aicsimageio for reading files. This would be particularly useful if your datasets are really large. If you use other plugins, you may need to set channel or time dimensions manually.

**Comment by Eddymorphling** [comment]
Thanks for the quick response @pr4deepr. Updating to 0.1.9 and using aiscimageio seems to have fixed the issue. I will now start using for my llsm datasets :)

**Comment by pr4deepr** [comment]
Thanks @Eddymorphling . 
If you are interested in segmentation or analyzing your data within this interface, you may find the "Workflows" section  of the wiki useful. 
https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/wiki
Let me know if it isn't clear.
