### ISSUE TITLE
Better ROI selection UI

### ISSUE THREAD

**Issue by multimeric** [BioimageAnalysisCoreWEHI/napari_lattice#90]
Moved from #84

TODOs:
 * [x] Modify the ROI selector to list all shapes from all layers, rather than just listing shape layers
 * [x] Synchronise the shape selection with the ROI box
 * [ ] Warn user in the preview box if multiple ROIs are selected

**Comment by multimeric** [comment]
Here's a demo of the current functionality:

[napari.webm](https://github.com/user-attachments/assets/38ed5b60-df21-4431-ae18-f8b721c1203f)

**Comment by pr4deepr** [comment]
Yup, this looks great.
Does it work for shapes in a single layer or shapes across multiple layers?

**Comment by multimeric** [comment]
Okay I've fixed that up, here's an example:

[napari2.webm](https://github.com/user-attachments/assets/e8818145-8612-4850-a0df-20f3b2728f2c)

**Comment by pr4deepr** [comment]
Great, this looks really nice.
